### PR TITLE
(SIMP-4747) Allow multiple profs & add stig prof

### PR DESCRIPTION
**Pull request by lnemsick-simp**
- Added ability to select one or more audit profiles.  When multiple
  profiles are selected, their rules are effectively concatenated in
  the order in which the profiles are listed in
  auditd::default_audit_profiles.
- The following API Changes were made in support of multiple audit
  profiles:
  - auditd::config and auditd::config::audit_profiles::simp are now
    private.
  - `auditcl` global configuration options that were in
    auditd::config::audit_profiles::simp are now in auditd, instead.
    They were moved because they are now applied to the set of audit
    profiles selected, not just the 'simp' audit profile.
  - Global audit rule configuration has been moved from
    auditd::config::audit_profiles::simp to a new class,
    auditd::config::audit_profiles.
  - Some previously hard-coded, internal configuration is now exposed
    as data-in-modules.
  - Some configuration parameter names have been changed for clarity.
- Added 'stig' audit profile which manages rules that match DISA STIG
  checks, exactly.
  - For CentOS7, includes watchs for binaries in the real paths (/usr/bin,
    /usr/sbin) and linked paths (/bin,/sbin), because of inconsistencies
    in both the STIG and the Inspec and OSCAP scans.  This is only
    for
- 'simp' profile changes:
  - Fixed umask syscall rules.  These rules require arch filters.
  - Fixed clock_settime syscall rules.  Per the sample STIG audit rules
    packaged in the auditd RPM, these rules require an additional filter.
  - Fixed bug in which /var/log/tallylog was grouped with session
    instead of logins.
  - Fixed bug in which the /etc/pam.d watch rule had the wrong tag
  - Added missing syscalls to su-root basic, aggressive, and insane
    syscall lists
  - Added an option to audit the execution of rename/remove operations
    for non-service users (rename', 'renameat', rmdir', 'unlink', and
    'unlinkat', for DISA STIG)
  - Added watch rules for /etc/hostname and /etc/NetworkManager (for
    centos7) pulled from the sample STIG audit rules packaged in the
    auditd RPM.
  - For CentOS7, added watchs for binaries in the real paths (/usr/bin,
    /usr/sbin) and linked paths (/bin,/sbin), because of inconsistencies
    in both the STIG and the Inspec and OSCAP scans.

- Other changes
  - Replaced params.pp with simplib::assert_metadata
  - Moved some of the logic buried in templates into manifests and/or
    data-in-modules
  - Switched a few templates to epp format
  - Beefed up class documentation
  - Removed outdated info that should be in REFERENCE.md from README.md
  - Tests, tests, and more tests

SIMP-4747 #close
SIMP-4748 #close

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@lnemsick-simp Would like to see the 'all rules' expected test output include everything up to `insane`

**Comment by trevor-vaughan** [comment]
@lnemsick-simp Rule ordering seems fine from what I can tell. We may want to expand the file watches based on your observations that the currently used format is legacy, but that can wait if necessary.

**Comment by trevor-vaughan** [comment]
:clock1: https://gitlab.com/simp/pupmod-simp-auditd/pipelines/24407435

**Comment by lnemsick-simp** [comment]
Tests are failing because gitlab runners are using older vboxes than I used in development.  I'll try to adjust the tests to handle the differences.

**Comment by lnemsick-simp** [comment]
:heavy_check_mark: https://gitlab.com/simp/pupmod-simp-auditd/pipelines/24539985

**Pull request merged**
