### PR TITLE
add EL9 support

### PR DESCRIPTION
**Pull request by jhoblitt**
Depends upon:
- #161
  - https://github.com/simp/pupmod-simp-logrotate/pull/64
  - https://github.com/simp/pupmod-simp-logrotate/pull/65

### CODE REVIEW

**Comment by canihavethisone** [comment]
Can we bump up stdlib?

**Comment by jhoblitt** [comment]
I've found a possible issue with EL9 I need to investigate.

**Comment by jhoblitt** [comment]
It seems that simp-rspec-puppet-facts-3.5.1 does not have oraclelinux-9 data in it, which was the source of the test failure.

**Comment by jhoblitt** [comment]
Ping?

**Comment by silug** [comment]
> It seems that simp-rspec-puppet-facts-3.5.1 does not have oraclelinux-9 data in it, which was the source of the test failure.

The latest should have data for all the EL9 variants now.  Mind rebasing and giving it a try?

**Comment by jhoblitt** [comment]
26 mins and counting... is that normal?

**Comment by silug** [comment]
If you could rebase one more time and grab a3249d70310ec7de45ee2e14625d872c9367aea6 from https://github.com/silug/pupmod-simp-auditd/pull/new/el9, I can get this merged immediately.

Thanks for the contribution, and sorry for the delay.

**Pull request closed without merging**
